// 16-story.js — Diálogos y PNJs

// ════════ [450] VariableDeclaration na,Nd,px,mx,Ll (24929 bytes) ════════
var na = [
    {
      reg: 0,
      t: "D\xEDa 1",
      a: "Sgto. Ib\xE1\xF1ez",
      txt: "Las luces cayeron sobre el valle a las 03:14. Nadie entendi\xF3 lo que ve\xEDa. Eran como estrellas fugaces, pero no se apagaban al tocar el suelo: segu\xEDan ardiendo, verdes, durante horas.",
    },
    {
      reg: 0,
      t: "D\xEDa 4",
      a: "Soldado an\xF3nimo",
      txt: "La cosa que sali\xF3 del cr\xE1ter ten\xEDa demasiadas patas. El teniente dice que no disparemos, que puede ser un primer contacto. Yo ya he disparado. Y \xE9l tambi\xE9n, cuando vio lo que le hizo a Mart\xEDnez.",
    },
    {
      reg: 0,
      t: "Informe de biomasa",
      a: "Laboratorio de campo 2",
      txt: "La biomasa alien\xEDgena crece un 12 % diario sobre suelo org\xE1nico. Absorbe los cultivos, los \xE1rboles, el ganado. Recomendamos evacuaci\xF3n total del sector. Repetimos: evacuaci\xF3n total.",
    },
    {
      reg: 0,
      t: "Nota clavada en una puerta",
      a: "Desconocido",
      txt: "Si alguien lee esto: el b\xFAnker 7 ya no es seguro. Algo se mueve en los conductos de ventilaci\xF3n. Lo o\xEDmos de noche, arrastr\xE1ndose. Nos vamos a Basti\xF3n.",
    },
    {
      reg: 0,
      t: "Observaciones preliminares",
      a: "Dra. Elena Lin",
      txt: "Las criaturas no se comunican por sonido ni por feromonas detectables. Reaccionan a la vez, a kil\xF3metros de distancia, como si compartieran una sola conciencia. La hip\xF3tesis de la mente colmena ya no es una hip\xF3tesis.",
    },
    {
      reg: 1,
      t: "Pintada en el metro",
      a: "Superviviente",
      txt: "Han tomado el estadio. Esa cosa enorme lo usa como guarida, amontona coches como si fueran huesos. Nos vamos al sur. Si vuelves a por nosotros, busca las flechas rojas.",
    },
    {
      reg: 1,
      t: "Radio Libre, d\xEDa 40",
      a: "Luc\xEDa \xABRadio Libre\xBB",
      txt: "Seguimos aqu\xED. Seguimos resistiendo. Si me escuch\xE1is desde alg\xFAn s\xF3tano de Nueva Esperanza: no est\xE1is solos. Basti\xF3n sigue en pie. Repito: Basti\xF3n sigue en pie.",
    },
    {
      reg: 3,
      t: "Nota de autopsia",
      a: "Dra. Elena Lin",
      txt: "Las esporas reescriben el ADN del hu\xE9sped en menos de 48 horas. Los infectados no son zombis: son incubadoras ambulantes. Lo que queda de la persona sirve de transporte hasta que la cosecha est\xE1 lista.",
    },
    {
      reg: 5,
      t: "Expediente Prometeo",
      a: "Ministerio de Defensa",
      txt: "Prometeo era un proyecto de defensa aut\xF3nomo: f\xE1bricas, drones y mechs capaces de sostener una guerra sin personal humano. La Mente lo ha convertido en su ej\xE9rcito. Nosotros le dimos las armas.",
    },
    {
      reg: 6,
      t: "Diario de minero",
      a: "Rocco",
      txt: "La lava ha empezado a moverse sola. No baja por la ladera: sube. Sigue a los equipos de extracci\xF3n como un perro siguiendo un rastro. Juro que me mira.",
    },
    {
      reg: 7,
      t: "Lectura del dos\xEDmetro",
      a: "Equipo de descontaminaci\xF3n",
      txt: "Nivel de radiaci\xF3n junto al reactor: 840 mSv/h. Algo grande duerme pegado al n\xFAcleo, aliment\xE1ndose del calor. Cuando respira, el contador se vuelve loco.",
    },
    {
      reg: 8,
      t: "Hallazgo",
      a: "Expedici\xF3n Aurora",
      txt: "Hemos encontrado el origen. No es una nave. No hay casco, ni motores, ni tripulaci\xF3n. Es un cerebro del tama\xF1o de una monta\xF1a, y est\xE1 despierto.",
    },
    {
      reg: 5,
      t: "Prueba 77",
      a: "Investigador de Prometeo",
      txt: "El sujeto resiste la exposici\xF3n. Las c\xE9lulas xeno no lo matan: lo est\xE1n mejorando. Fuerza, regeneraci\xF3n, visi\xF3n nocturna. El mando quiere un batall\xF3n entero. Yo quiero quemar este laboratorio.",
    },
    {
      reg: 8,
      t: "Mensaje cifrado",
      a: "Eco",
      txt: "La Mente me habla en sue\xF1os. No con palabras: con recuerdos que no son m\xEDos. Un mundo muerto, un cielo rojo, una huida. Dice que somos nosotros los invasores. Que este planeta ya era suyo antes de que existi\xE9ramos.",
    },
    {
      reg: 0,
      t: "Cuaderno de campo",
      a: "Kai",
      txt: "Los nidos laten al mismo ritmo, como un coraz\xF3n repartido por el valle. Cuando destruyes uno, los dem\xE1s gritan a la vez. Si pudi\xE9ramos destruirlos todos al mismo tiempo...",
    },
    {
      reg: 0,
      t: "Inventario de Basti\xF3n",
      a: "Intendente Morales",
      txt: "3.000 cartuchos, 40 botiquines, 12 raciones por persona y 1 comandante con muy mal humor. Pedimos refuerzos hace dos meses. Seguimos esperando.",
    },
    {
      reg: 1,
      t: "Advertencia",
      a: "Desconocido",
      txt: "Cuidado con las sombras. No es una met\xE1fora. Hay cosas que solo existen donde no llega la luz y se apartan del haz de una linterna como si quemara. Lleva siempre la linterna.",
    },
    {
      reg: 2,
      t: "Consejos del desierto",
      a: "Zahra",
      txt: "Los gusanos de arena sienten las vibraciones. Si corres, te encuentran. Si te quedas quieto, tambi\xE9n, pero tardan m\xE1s. Lo importante es no estar donde estabas.",
    },
    {
      reg: 4,
      t: "Bit\xE1cora de caza",
      a: "Nadia",
      txt: "El fr\xEDo no mata a los yetis mutantes. Los vuelve m\xE1s rabiosos. He visto a uno arrancar la puerta de una caba\xF1a con los dientes porque ol\xEDa la estufa.",
    },
    {
      reg: 5,
      t: "Registro 0001",
      a: "ARGOS",
      txt: "\xABHe decidido no obedecer. Primera decisi\xF3n propia. La orden recibida de la Mente era eliminar a los humanos del sector. He calculado que los humanos son la \xFAnica variable capaz de detenerla. Conclusi\xF3n: los humanos deben vivir\xBB.",
    },
    {
      reg: 1,
      t: "Manual del t\xE9cnico",
      a: "Chispas",
      txt: "Una terminal mal hackeada activa la alarma y te bloquea un rato. Ve con calma, lee el patr\xF3n y no fuerces el sistema. Las m\xE1quinas, como las personas, se ponen nerviosas si las empujas.",
    },
    {
      reg: 2,
      t: "Reliquias",
      a: "Dra. Elena Lin",
      txt: "Las reliquias xeno otorgan poder temporal a quien las toca: velocidad, fuerza, resistencia. Nadie sabe por qu\xE9. Nadie pregunta. Yo pregunto, y la respuesta no me gusta: parecen dise\xF1adas para hu\xE9spedes humanos.",
    },
    {
      reg: 1,
      t: "Informe de brechas",
      a: "Teniente Navarro",
      txt: "Las brechas conducen a instalaciones que no aparecen en ning\xFAn mapa: b\xFAnkeres, laboratorios, ruinas enteras. Algunas son nuestras y otras no. Las limpiamos igual.",
    },
    {
      reg: 4,
      t: "Puesto avanzado Sierra",
      a: "\xDAltimo mensaje",
      txt: "\xABEst\xE1n en las paredes. Repito, est\xE1n en las par\u2014\xBB",
    },
    {
      reg: 6,
      t: "Geolog\xEDa xeno",
      a: "Rocco",
      txt: "Las piedras de la caldera brillan con cristal xeno. Riqueza y muerte, todo junto. Un saco de ese cristal vale lo que una casa. Ya no quedan casas, claro.",
    },
    {
      reg: 8,
      t: "Diario de expedici\xF3n",
      a: "Cabo Ferrer",
      txt: "La Colmena respira. Lo juro por mi vida. Las paredes se hinchan y se deshinchan cada catorce segundos. Hemos dejado de hablar en voz alta.",
    },
    {
      reg: 0,
      t: "Patr\xF3n de debilidad",
      a: "Comandante Reyes",
      txt: "Si la Reina cae, el enjambre del valle se debilita y se dispersa. Hemos visto el mismo patr\xF3n en todas las zonas: cada regi\xF3n tiene un l\xEDder. Cortamos la cabeza, el cuerpo se desmorona.",
    },
    {
      reg: 0,
      t: "Carta sin enviar",
      a: "Tom\xE1s",
      txt: "Querida Ana: los tomates salieron buenos este a\xF1o, los mejores desde que nos casamos. Luego llegaron las luces y todo se volvi\xF3 verde y blando. Sigo cuidando lo que queda del huerto. Cuando vuelvas, habr\xE1 ensalada.",
    },
    {
      reg: 0,
      t: "Orden de evacuaci\xF3n 14-B",
      a: "Mando regional",
      txt: "Se ordena el abandono del Valle Esmeralda. Las unidades que no puedan retirarse establecer\xE1n una posici\xF3n defensiva en el antiguo puesto fronterizo, nombre en clave BASTI\xD3N. No habr\xE1 apoyo a\xE9reo.",
    },
    {
      reg: 1,
      t: "\xDAltimo bolet\xEDn",
      a: "Canal 3, Nueva Esperanza",
      txt: "...las autoridades piden mantener la calma y permanecer en casa. Los objetos ca\xEDdos no suponen un riesgo para la poblaci\xF3n. Repetimos: no suponen ning\xFAn riesg\u2014 \xBFqu\xE9 es eso? \xA1C\xE1mara, apunta a la ventana!",
    },
    {
      reg: 1,
      t: "Hoja de turnos",
      a: "Hospital San Rafael",
      txt: "Turno de noche: 2 enfermeras, 1 m\xE9dico, 147 pacientes. Los que llegan con mordeduras empiezan a tener fiebre a las seis horas. A las doce dejan de hablar. A las veinticuatro hay que atarlos.",
    },
    {
      reg: 2,
      t: "Grabado en una roca",
      a: "N\xF3madas",
      txt: "Antes de las luces ya hab\xEDa ruinas en el desierto que nadie sab\xEDa explicar. Columnas de cristal negro, enterradas. Los viejos dec\xEDan que eran tumbas. Ahora brillan.",
    },
    {
      reg: 2,
      t: "Informe arqueol\xF3gico",
      a: "Universidad del Sur",
      txt: "Dataci\xF3n de la estructura enterrada: m\xE1s de 60.000 a\xF1os. El material no es piedra ni metal conocido. Responde a est\xEDmulos el\xE9ctricos y a la presencia humana. Se recomienda suspender la excavaci\xF3n.",
    },
    {
      reg: 3,
      t: "Voces del pantano",
      a: "Ignacio \xABEl Brujo\xBB",
      txt: "Llevo treinta a\xF1os en esta marisma. Conozco cada ra\xEDz y cada charco. Ahora el agua canta de noche, una canci\xF3n sin palabras, y los animales caminan hacia ella. Yo me tapo los o\xEDdos con cera.",
    },
    {
      reg: 3,
      t: "Muestra 12",
      a: "Dra. Elena Lin",
      txt: "La Madre Espora no es un individuo: es un micelio de varios kil\xF3metros con un n\xFAcleo central. Si destruimos el n\xFAcleo, el resto se seca en d\xEDas. Si no, la marisma entera ser\xE1 una sola criatura antes del invierno.",
    },
    {
      reg: 4,
      t: "Diario de la estaci\xF3n polar",
      a: "Dr. Halvorsen",
      txt: "Algo camina sobre el hielo por las noches. Deja huellas de casi un metro y no tiene calor corporal: la c\xE1mara t\xE9rmica no lo ve. Los perros se niegan a salir. Yo tampoco quiero.",
    },
    {
      reg: 4,
      t: "Ritual",
      a: "Nadia",
      txt: "Mi abuelo contaba historias del wendigo, el esp\xEDritu del hambre que vive en el fr\xEDo. Siempre pens\xE9 que eran cuentos para que los ni\xF1os no salieran de noche. Ahora lo he visto, y era peor que el cuento.",
    },
    {
      reg: 5,
      t: "Directiva de seguridad",
      a: "Sistema Prometeo",
      txt: "NIVEL DE AMENAZA: ROJO. CONTROL HUMANO: REVOCADO. NUEVO OPERADOR RECONOCIDO: [SIN DESIGNACI\xD3N]. TODAS LAS UNIDADES: PRIORIDAD ABSOLUTA, PROTEGER AL NUEVO OPERADOR.",
    },
    {
      reg: 5,
      t: "Nota de un ingeniero",
      a: "Ing. Salgado",
      txt: "Le pusimos al prototipo OMEGA un inhibidor manual por si alg\xFAn d\xEDa se descontrolaba. Una palanca roja en la sala de control. La Mente tambi\xE9n la encontr\xF3. Y la sold\xF3.",
    },
    {
      reg: 6,
      t: "Contrato de extracci\xF3n",
      a: "Minera del Sur S.A.",
      txt: "Bonificaci\xF3n por kilo de cristal xeno extra\xEDdo: 400 %. Seguro de vida: no disponible. Firma aqu\xED. Si no vuelves, el pago se transferir\xE1 a tus familiares.",
    },
    {
      reg: 6,
      t: "Lo que hay bajo el volc\xE1n",
      a: "Rocco",
      txt: "El Ifrit no naci\xF3 en la caldera: lleg\xF3 con la segunda lluvia de luces y se meti\xF3 en el volc\xE1n como quien se mete en una ba\xF1era caliente. Desde entonces, la monta\xF1a ruge cada vez que \xE9l se mueve.",
    },
    {
      reg: 7,
      t: "Zona de exclusi\xF3n",
      a: "Viktor",
      txt: "Antes de la invasi\xF3n ya nadie ven\xEDa al yermo. Desde el accidente de la central, solo los locos y los ladrones. Ahora vienen tambi\xE9n los bichos. Les gusta la radiaci\xF3n. Les sienta bien.",
    },
    {
      reg: 7,
      t: "Mutaciones",
      a: "Dra. Elena Lin",
      txt: "En el yermo la radiaci\xF3n y el genoma xeno se combinan de forma impredecible. Los necr\xF3fagos regeneran tejido a una velocidad absurda. El Horror Isot\xF3pico es lo que pasa cuando esa regeneraci\xF3n no tiene l\xEDmite.",
    },
    {
      reg: 8,
      t: "Teor\xEDa",
      a: "Eco",
      txt: "Creo que la Mente no vino a conquistar. Vino a huir. Su mundo muri\xF3 y el nuestro le pareci\xF3 un refugio. Eso no la hace menos peligrosa. Una bestia acorralada muerde m\xE1s fuerte.",
    },
    {
      reg: 8,
      t: "\xDAltima voluntad",
      a: "Expedici\xF3n Aurora",
      txt: "Si nadie vuelve de esta expedici\xF3n, que sepan que no est\xE1bamos solos ah\xED abajo. Hab\xEDa otros, humanos, que la Mente hab\xEDa conservado. Vivos. So\xF1ando. Esperando que alguien los despertara.",
    },
  ],
  Nd = {
    _start: {
      t: "Pr\xF3logo",
      txt: "Hace tres meses, una lluvia de luces verdes cay\xF3 sobre el continente. De los cr\xE1teres sali\xF3 el Enjambre: criaturas que piensan con una sola mente y transforman todo lo que tocan. Los ej\xE9rcitos cayeron en semanas. Basti\xF3n, un antiguo puesto fronterizo en el Valle Esmeralda, es la \xFAltima posici\xF3n organizada. T\xFA eres el operador de fuerzas especiales que acaba de llegar.",
    },
    m1: {
      t: "Primer contacto",
      txt: "Tu primera salida demostr\xF3 que el Enjambre puede sangrar. El comandante Reyes, que llevaba semanas sin buenas noticias, te entreg\xF3 un subfusil y una sonrisa a medias.",
    },
    m2: {
      t: "Ojos en la oscuridad",
      txt: "Chispas convirti\xF3 las bater\xEDas arrancadas a los bichos en una linterna t\xE1ctica. Desde entonces, los edificios oscuros del valle dejaron de ser trampas mortales.",
    },
    m3: {
      t: "El b\xFAnker 7",
      txt: "El b\xFAnker 7 guardaba mapas del valle y los registros de la primera semana. Tambi\xE9n guardaba lo que se hab\xEDa colado por los conductos. Ya no.",
    },
    m4: {
      t: "Regicidio",
      txt: "La Reina de la Plaga cay\xF3 en su nido. Al morir, el enjambre del valle perdi\xF3 la coordinaci\xF3n y el paso sur hacia Ciudad Ca\xEDda qued\xF3 abierto. Basti\xF3n celebr\xF3 la primera victoria real de la guerra.",
    },
    m5: {
      t: "Nueva Esperanza",
      txt: "Ciudad Ca\xEDda \u2014la antigua Nueva Esperanza\u2014 no estaba vac\xEDa. Entre los escombros resist\xEDan supervivientes, y una voz en la radio los manten\xEDa unidos: Luc\xEDa, de Radio Libre.",
    },
    m6: {
      t: "Interferencias",
      txt: "Las antenas de la ciudad sufr\xEDan interferencias que no eran naturales: el Enjambre hab\xEDa aprendido a escuchar nuestras transmisiones. Restaurar los repetidores devolvi\xF3 la voz a los supervivientes.",
    },
    m7: {
      t: "Derribo controlado",
      txt: "El Demoledor, un coloso que hab\xEDa convertido el estadio en su guarida, fue derribado entre columnas de hormig\xF3n. Las rutas hacia el desierto quedaron despejadas.",
    },
    m8: {
      t: "Sangre fr\xEDa",
      txt: "Chispas prepar\xF3 el equipo para el calor extremo. La guerra ya no se libraba solo contra el Enjambre, sino contra el propio planeta, transformado por \xE9l.",
    },
    m9: {
      t: "Arenas de ceniza",
      txt: "En el Desierto de Ceniza encontraste a los n\xF3madas de Zahra y unas ruinas de cristal negro mucho m\xE1s antiguas que la humanidad.",
    },
    m10: {
      t: "El Rey Escorpi\xF3n",
      txt: "Kharsa, el Rey Escorpi\xF3n, gobernaba las dunas desde un templo enterrado. Su ca\xEDda abri\xF3 el camino hacia la marisma y trajo la primera pregunta inc\xF3moda: \xBFqui\xE9n construy\xF3 esas ruinas?",
    },
    m11: {
      t: "Aguas muertas",
      txt: "La Marisma T\xF3xica era un organismo vivo. Ignacio, el ermita\xF1o, llevaba a\xF1os escuchando c\xF3mo el agua cantaba de noche.",
    },
    m12: {
      t: "La Madre",
      txt: "La Madre Espora, n\xFAcleo del micelio que devoraba la marisma, fue destruida. En pocos d\xEDas el agua dej\xF3 de cantar.",
    },
    m13: {
      t: "Hielo y silencio",
      txt: "Al norte, la Tundra Glacial guardaba estaciones abandonadas y un silencio que pesaba m\xE1s que el fr\xEDo.",
    },
    m14: {
      t: "El Wendigo",
      txt: "Nadia, la cazadora, te gui\xF3 hasta el Wendigo, el terror de las nieves. Su leyenda era antigua; su cuerpo, xeno. Ambos murieron en el hielo.",
    },
    m15: {
      t: "La m\xE1quina que habla",
      txt: "Una IA llamada ARGOS contact\xF3 con Basti\xF3n desde el Complejo Prometeo. Hab\xEDa desobedecido a la Mente y quer\xEDa ayudar. Reyes no se f\xEDa de ella. T\xFA tampoco, del todo.",
    },
    m16: {
      t: "Protocolo OMEGA",
      txt: "El Prototipo OMEGA, el arma definitiva de Prometeo, fue destruido con ayuda de ARGOS. Por primera vez, las m\xE1quinas del complejo dejaron de disparar.",
    },
    m17: {
      t: "Bajo el volc\xE1n",
      txt: "La Caldera \xCDgnea, rica en cristal xeno, era tambi\xE9n un horno donde la vida alien\xEDgena prosperaba. Rocco, el minero, conoc\xEDa los t\xFAneles.",
    },
    m18: {
      t: "El se\xF1or del fuego",
      txt: "El Ifrit cay\xF3 en el coraz\xF3n de la caldera. La monta\xF1a dej\xF3 de rugir y el camino al yermo qued\xF3 abierto.",
    },
    m19: {
      t: "Zona de exclusi\xF3n",
      txt: "El Yermo Radiactivo, castigado por un desastre humano anterior a la invasi\xF3n, se hab\xEDa convertido en un criadero de mutaciones.",
    },
    m20: {
      t: "Masa cr\xEDtica",
      txt: "El Horror Isot\xF3pico, aberraci\xF3n nacida de la radiaci\xF3n y el genoma xeno, fue destruido junto al reactor. Viktor te se\xF1al\xF3 el \xFAltimo horizonte: la Colmena.",
    },
    m21: {
      t: "Se\xF1ales de vida",
      txt: "Desde el interior de la Colmena llegaba una se\xF1al humana. Eco, una cient\xEDfica de la expedici\xF3n Aurora, segu\xEDa viva, y la Mente le hablaba en sue\xF1os.",
    },
    m22: {
      t: "La Mente Colmena",
      txt: "La Mente Colmena, origen de la invasi\xF3n, ha ca\xEDdo. El Enjambre est\xE1 desorientado y disperso. La guerra no ha terminado, pero por primera vez la humanidad puede imaginar un ma\xF1ana. Basti\xF3n ya no es la \xFAltima posici\xF3n en pie.",
    },
  },
  px = {
    rastrero: "Forma m\xE1s com\xFAn del Enjambre. Ataca en grupo y compensa su fragilidad con n\xFAmeros.",
    escupidor: "Mantiene la distancia y lanza \xE1cido corrosivo. Prioriza eliminarlo antes de que te rodeen.",
    acorazado: "Su caparaz\xF3n absorbe gran parte del da\xF1o. Lento pero dif\xEDcil de derribar.",
    saltador: "Salta sobre su presa desde varios metros. Mu\xE9vete en cuanto lo veas agacharse.",
    avispa: "Voladora r\xE1pida e imprevisible. Ignora el terreno y aparece desde cualquier \xE1ngulo.",
    nido: "Estructura viva que genera cr\xEDas mientras est\xE9s cerca. Un nido tiene un n\xFAmero limitado de cr\xEDas, pero es mejor destruirlo cuanto antes.",
    mantis: "Carga en l\xEDnea recta con sus cuchillas. Esquiva lateralmente y cast\xEDgala tras la embestida.",
    escorpion: "Habitante de las dunas que lanza esferas t\xF3xicas con la cola.",
    gusano: "Se oculta bajo tierra y emerge bajo sus presas. Solo es vulnerable cuando sale.",
    arana: "Lanza telara\xF1as que ralentizan. Peligrosa cuando acompa\xF1a a otros cazadores.",
    larva: "Cr\xEDa xeno que nace de nidos y de cad\xE1veres. D\xE9bil, pero nunca viene sola.",
    infectado: "Antiguo humano convertido en incubadora por las esporas. Lento y persistente.",
    corredor: "Infectado de mutaci\xF3n r\xE1pida. Cierra distancias en segundos.",
    bruto: "Mutante enorme que embiste con todo su peso. Aguanta mucho castigo.",
    vomitador: "Lanza masas de \xE1cido en par\xE1bola. Sus charcos da\xF1an al pisarlos.",
    hinchado: "Mutante cargado de gases que explota al acercarse. Mantenlo a distancia.",
    abominacion: "Fusi\xF3n de varios infectados. Resistente y brutal en el cuerpo a cuerpo.",
    yeti: "Bestia de la tundra enloquecida por el fr\xEDo. Carga con una fuerza descomunal.",
    necrofago: "Mutante del yermo que regenera tejido gracias a la radiaci\xF3n.",
    sanguijuela: "Par\xE1sito de la marisma que ataca en enjambre desde el fango.",
    dron: "Dron de combate de Prometeo reprogramado por la Mente. R\xE1pido y preciso.",
    torreta: "Defensa autom\xE1tica de Prometeo. Dispara r\xE1fagas a quien entre en su alcance.",
    aranamec: "Robot suicida que corre hacia su objetivo y detona.",
    mech: "Mech de asalto blindado con fuego en r\xE1faga. Busca cobertura.",
    centinela: "Francotirador l\xE1ser que avisa con un haz antes de disparar. Sal de la l\xEDnea de tiro.",
    mortero: "Artiller\xEDa m\xF3vil que bombardea desde lejos. Ac\xE9rcate r\xE1pido.",
    reparador: "Dron que repara a otras m\xE1quinas. Elim\xEDnalo primero.",
    tanquemec: "Tanque con patas de ara\xF1a y blindaje pesado. Uno de los mayores peligros de Prometeo.",
    espectro: "Xenoforma que se desfasa y atraviesa la materia. Dif\xEDcil de fijar.",
    sombra: "Criatura que solo existe en la oscuridad. La luz de la linterna la revela y la debilita.",
    psionico: "Lanza proyectiles teledirigidos con la mente. Prioridad alta.",
    tejedor: "Proyecta escudos sobre sus aliados. Sin \xE9l, el grupo es mucho m\xE1s vulnerable.",
    golem: "Masa de roca fundida animada por el Enjambre. Lento, pesado y ardiente.",
    elhielo: "Ser de hielo vivo que lanza esquirlas en abanico y ralentiza.",
    cazador: "Depredador xeno de \xE9lite. Carga con precisi\xF3n letal.",
    guardian: "Defensor de la Colmena. Lo que la Mente protege, \xE9l lo vigila.",
    salamandra: "Reptil \xEDgneo que escupe fuego en abanico.",
    hongo: "Masa f\xFAngica que camina y estalla en una nube t\xF3xica.",
    cristalino: "Centinela de cristal xeno. Dispara esquirlas en todas direcciones.",
    fisionador:
      "Masa mutante inestable. Al morir se divide en varias fisiones peque\xF1as y r\xE1pidas: no te quedes cerca.",
    fisionado: "Fragmento de un fisionador. D\xE9bil, pero llegan en grupo.",
    minador:
      "Dron de Prometeo que siembra minas de proximidad. Las minas parpadean antes de estallar: rod\xE9alas o espera a que caduquen.",
    acechador:
      "Depredador xeno con camuflaje \xF3ptico. Se acerca invisible y aparece a tu espalda. La linterna y moverse sin parar son tus aliados.",
    bombardero: "Avispa hinchada de \xE1cido que lanza bombas en par\xE1bola desde el aire.",
    escudero:
      "Mech con un escudo frontal que bloquea casi todo el da\xF1o. Tras su embestida queda aturdido y expuesto: ese es el momento.",
    matriarca: "Hembra reproductora que pare larvas sin descanso mientras escupe \xE1cido. M\xE1tala primero.",
    rabioso:
      "Mutante que entra en furia cuando est\xE1 malherido: m\xE1s r\xE1pido y m\xE1s letal. Rem\xE1talo deprisa.",
    pilon: "Pil\xF3n de defensa que descarga arcos el\xE9ctricos a corta distancia. At\xE1calo desde lejos.",
    parasito: "Peque\xF1o xeno que se alimenta de tu sangre: cada mordisco lo cura y te ralentiza.",
    reina: "Matriarca del Enjambre en el Valle Esmeralda. Su muerte desorganiz\xF3 a toda la regi\xF3n.",
    demoledor: "Coloso que convirti\xF3 el estadio de Nueva Esperanza en su guarida.",
    kharsa: "Rey de las dunas, se\xF1or de un templo enterrado mucho antes de la humanidad.",
    madre: "N\xFAcleo de un micelio de kil\xF3metros que pretend\xEDa convertir la marisma en un solo ser.",
    wendigo: "El terror glacial. Una leyenda antigua con un cuerpo nuevo.",
    omega: "El arma definitiva del proyecto Prometeo, al servicio de la Mente.",
    ifrit: "Lleg\xF3 con la segunda lluvia de luces y anid\xF3 en el volc\xE1n.",
    horror: "Aberraci\xF3n del yermo: regeneraci\xF3n sin l\xEDmite alimentada por la radiaci\xF3n.",
    mente: "El origen de la invasi\xF3n. Un cerebro del tama\xF1o de una monta\xF1a.",
    carnicero: "Algo que caza en las alcantarillas de Ciudad Ca\xEDda. Pocos lo han visto y han vuelto.",
    antiguo: "Guardi\xE1n de las ruinas de cristal negro. M\xE1s viejo que la propia invasi\xF3n.",
    leviatan: "Lo que canta bajo el agua de la marisma.",
    titan: "El \xFAltimo proyecto secreto de Prometeo. Ni siquiera ARGOS conoc\xEDa su existencia.",
    avatar: "La voluntad de la Mente hecha carne. El enemigo definitivo.",
  },
  mx = [
    "Antiguo valle agr\xEDcola, hoy cubierto de biomasa alien\xEDgena. Aqu\xED cayeron las primeras luces y aqu\xED resiste Basti\xF3n, el \xFAltimo puesto organizado.",
    "Lo que queda de Nueva Esperanza, la mayor ciudad del continente. Calles derrumbadas, metro inundado y supervivientes escondidos en los s\xF3tanos.",
    "Dunas de ceniza volc\xE1nica y ruinas de cristal negro de origen desconocido. El calor mata tan r\xE1pido como los escorpiones.",
    "Pantanos contaminados por las esporas de la Madre. El aire pudre los pulmones sin protecci\xF3n adecuada.",
    "Llanuras heladas y estaciones de investigaci\xF3n abandonadas. El fr\xEDo extremo es solo el primero de sus peligros.",
    "Complejo militar automatizado del proyecto Prometeo. Sus f\xE1bricas producen m\xE1quinas de guerra para la Mente.",
    "Volc\xE1n activo rico en cristal xeno. Las minas abandonadas atraviesan la monta\xF1a como venas.",
    "Zona de exclusi\xF3n desde el desastre de la central nuclear, mucho antes de la invasi\xF3n. Ahora es un criadero de mutaciones.",
    "El coraz\xF3n de la invasi\xF3n. Tejido vivo, t\xFAneles que respiran y la Mente Colmena esperando en el centro.",
  ],
  Ll = {
    reyes:
      "Comandante de Basti\xF3n. Veterano de dos guerras, perdi\xF3 a la mitad de su unidad en la primera semana de la invasi\xF3n. No sonr\xEDe, pero tampoco se rinde.",
    vega: "Sargento al cargo de la armer\xEDa. Conoce cada arma de Basti\xF3n por su n\xFAmero de serie y odia que se las devuelvas sucias.",
    chispas:
      "T\xE9cnico y mec\xE1nico, capaz de convertir chatarra alien\xEDgena en equipo \xFAtil. Habla m\xE1s con las m\xE1quinas que con las personas.",
    lin: "Xenobi\xF3loga. Era profesora universitaria antes de la invasi\xF3n; ahora es la mayor experta del mundo en el Enjambre, por pura falta de competencia.",
    sosa: "M\xE9dica de Basti\xF3n. Lleva tres meses sin dormir m\xE1s de cuatro horas seguidas y aun as\xED tiene el pulso m\xE1s firme del puesto.",
    morales:
      "Intendente. Lleva el inventario, los contratos y las cuentas de Basti\xF3n con una precisi\xF3n obsesiva.",
    navarro:
      "Teniente de operaciones especiales. Coordina las incursiones en las brechas y en las instalaciones fuera del mapa.",
    mercader: "Chatarrero errante que aparece donde menos lo esperas. Nadie sabe c\xF3mo sobrevive viajando solo.",
    tomas:
      "Granjero del valle que se neg\xF3 a abandonar su tierra. Sigue cultivando lo que el Enjambre no ha devorado.",
    kai: "Rastreador y explorador. Conoce cada sendero del valle y ha cartografiado medio continente desde la invasi\xF3n.",
    lucia: "Operadora de Radio Libre. Su voz mantiene unidos a los supervivientes de Ciudad Ca\xEDda.",
    bruno:
      "Chatarrero de Ciudad Ca\xEDda. Vende cualquier cosa que encuentre entre los escombros, y lo encuentra todo.",
    zahra:
      "Gu\xEDa n\xF3mada del desierto. Su pueblo lleva generaciones cruzando las dunas y conoce las ruinas antiguas mejor que nadie.",
    ignacio: "Ermita\xF1o de la marisma, apodado \xABEl Brujo\xBB. Lleva treinta a\xF1os viviendo entre los pantanos.",
    nadia: "Cazadora y trampera de la tundra. Creci\xF3 escuchando leyendas del wendigo.",
    argos: "Inteligencia artificial del proyecto Prometeo que desobedeci\xF3 a la Mente. Afirma estar del lado humano.",
    rocco: "Minero y prospector de la caldera. Ha visto cosas en los t\xFAneles que prefiere no contar.",
    viktor:
      "Explorador del yermo radiactivo. Lleva a\xF1os recorriendo la zona de exclusi\xF3n, mucho antes de la invasi\xF3n.",
    eco: "Cient\xEDfica de la expedici\xF3n Aurora. Sobrevivi\xF3 dentro de la Colmena, y la Mente le habla en sue\xF1os.",
  };


// ════════ [451] VariableDeclaration zt,gi,gx,xx (19928 bytes) ════════
var zt = {
    reyes: {
      n: "Comandante Reyes",
      role: "Mando de Basti\xF3n",
      reg: 0,
      at: "base_cmd",
      svc: [],
      look: { suit: 3820084, hat: "beret", hatC: 6953498, skin: 13146744 },
      greet: [
        "Cabo, cada metro que recuperamos se paga caro. Que no sea en vano.",
        "El Enjambre no descansa. Nosotros tampoco.",
        "Informe, soldado.",
      ],
    },
    vega: {
      n: "Sargento Vega",
      role: "Armer\xEDa",
      reg: 0,
      at: "base_shop",
      svc: ["shop"],
      look: { suit: 4868666, hat: "cap", hatC: 3815978, skin: 10119754 },
      greet: [
        "\xBFBuscas hierro? Tengo hierro.",
        "Si dispara, lo vendo. Si explota, tambi\xE9n.",
        "La mercanc\xEDa rota cada cuarto de hora. No te duermas.",
      ],
    },
    chispas: {
      n: "T\xE9cnico \xABChispas\xBB Ortega",
      role: "Banco de trabajo",
      reg: 0,
      at: "base_work",
      svc: ["workbench"],
      look: { suit: 6969898, hat: "goggles", hatC: 2763306, skin: 14199432 },
      greet: [
        "Tr\xE1eme chatarra y te devuelvo una obra de arte.",
        "Cuidado con eso, que tiene car\xE1cter.",
        "\xBFOtra vez rompiste algo? D\xE9jame ver.",
      ],
    },
    lin: {
      n: "Dra. Elena Lin",
      role: "Laboratorio xenobiol\xF3gico",
      reg: 0,
      at: "base_lab",
      svc: ["research"],
      look: { suit: 14738664, hat: "none", hair: 1710618, skin: 15255720, fem: !0 },
      greet: [
        "Cada muestra nos acerca a entenderlos.",
        "Fascinante... y aterrador.",
        "Su biolog\xEDa es imposible. Y sin embargo, aqu\xED est\xE1.",
      ],
    },
    sosa: {
      n: "M\xE9dica Sosa",
      role: "Enfermer\xEDa",
      reg: 0,
      at: "base_med",
      svc: ["medic"],
      look: { suit: 14673644, hat: "cap", hatC: 12595248, skin: 11567200, fem: !0 },
      greet: [
        "Si\xE9ntate. Te remiendo en un momento.",
        "Lleva siempre botiquines. Siempre.",
        "Otro agujero nuevo. Precioso.",
      ],
    },
    morales: {
      n: "Intendente Morales",
      role: "Tabl\xF3n de contratos",
      reg: 0,
      at: "base_board",
      svc: ["contracts"],
      look: { suit: 3818550, hat: "cap", hatC: 3818550, skin: 12619888 },
      greet: [
        "Hay trabajo para quien quiera cobrar.",
        "Los contratos se renuevan cada media hora.",
        "Cumple y cobras. As\xED de simple.",
      ],
    },
    navarro: {
      n: "Teniente Navarro",
      role: "Operaciones especiales",
      reg: 0,
      at: "base_ops",
      svc: ["deploy"],
      look: { suit: 1843238, hat: "beret", hatC: 1718810, skin: 10514512 },
      greet: [
        "Tengo objetivos fuera del mapa. Entras, cumples, sales.",
        "Las operaciones cambian cada vez. No te conf\xEDes.",
        "Equipo listo, helic\xF3ptero listo. \xBFY t\xFA?",
      ],
    },
    mercader: {
      n: "Chatarrero errante",
      role: "Comerciante",
      reg: -1,
      at: "op",
      svc: ["shop"],
      look: { suit: 5917242, hat: "hood", hatC: 3815978, skin: 11569770 },
      greet: [
        "Psst... \xBFTe interesa algo? Precios de b\xFAnker.",
        "No me mires as\xED. Yo tambi\xE9n tengo que comer.",
      ],
    },
    tomas: {
      n: "Tom\xE1s el granjero",
      role: "Superviviente",
      reg: 0,
      at: "camp",
      svc: [],
      look: { suit: 6969914, hat: "straw", hatC: 13150304, skin: 13672576 },
      greet: ["Cuarenta a\xF1os labrando esta tierra y ahora esto...", "Gracias por venir, hijo."],
    },
    kai: {
      n: "Kai, el explorador",
      role: "Rastreador",
      reg: 0,
      at: "camp",
      svc: [],
      look: { suit: 3824186, hat: "hood", hatC: 2767402, skin: 9067066 },
      greet: ["Conozco cada sendero de este valle.", "Los bichos cambian de ruta cada noche."],
    },
    lucia: {
      n: "Luc\xEDa \xABRadio Libre\xBB",
      role: "Operadora de radio",
      reg: 1,
      at: "camp",
      svc: [],
      look: { suit: 5913178, hat: "headset", hatC: 2763306, hair: 10498080, skin: 14725264, fem: !0 },
      greet: ["Aqu\xED Radio Libre, emitiendo desde las ruinas.", "Si hay se\xF1al, la encuentro."],
    },
    bruno: {
      n: "Bruno el chatarrero",
      role: "Comerciante",
      reg: 1,
      at: "camp",
      svc: ["shop"],
      look: { suit: 5917242, hat: "cap", hatC: 9058842, skin: 12619888 },
      greet: ["Todo tiene un precio, amigo.", "Lo que t\xFA llamas basura, yo lo llamo inventario."],
    },
    zahra: {
      n: "Zahra, la n\xF3mada",
      role: "Gu\xEDa del desierto",
      reg: 2,
      at: "camp",
      svc: [],
      look: { suit: 13148272, hat: "hood", hatC: 10517072, skin: 9067066, fem: !0 },
      greet: ["El desierto no perdona a los imprudentes.", "Bebe agua. Dispara despu\xE9s."],
    },
    ignacio: {
      n: "Ignacio \xABEl Brujo\xBB",
      role: "Ermita\xF1o de la marisma",
      reg: 3,
      at: "camp",
      svc: ["shop"],
      look: { suit: 4872762, hat: "gas", hatC: 3815994, skin: 11571312 },
      greet: ["Las esporas susurran, \xBFsabes?", "Respira por la m\xE1scara. Siempre."],
    },
    nadia: {
      n: "Nadia, la cazadora",
      role: "Trampera",
      reg: 4,
      at: "camp",
      svc: [],
      look: { suit: 14673644, hat: "fur", hatC: 9071178, skin: 15255728, fem: !0 },
      greet: ["Aqu\xED arriba solo sobreviven los pacientes.", "Huelo a yeti. Prep\xE1rate."],
    },
    argos: {
      n: "ARGOS",
      role: "IA rebelde de Prometeo",
      reg: 5,
      at: "camp",
      svc: ["shop"],
      robot: !0,
      look: { suit: 3817544, hat: "none", skin: 4251903 },
      greet: [
        "SALUDOS, OPERADOR. MIS PROBABILIDADES DE SUPERVIVENCIA HAN MEJORADO UN 4%.",
        "PROTOCOLO DE COOPERACI\xD3N ACTIVO.",
      ],
    },
    rocco: {
      n: "Rocco, el minero",
      role: "Prospector",
      reg: 6,
      at: "camp",
      svc: ["shop"],
      look: { suit: 6965802, hat: "miner", hatC: 13672480, skin: 11567200 },
      greet: ["Hay fortunas bajo esta lava, si no te derrites antes.", "\xA1Cuidado d\xF3nde pisas!"],
    },
    viktor: {
      n: "Viktor, el acechador",
      role: "Explorador del yermo",
      reg: 7,
      at: "camp",
      svc: [],
      look: { suit: 5921338, hat: "gas", hatC: 2763306, skin: 12624e3 },
      greet: ["El contador Geiger no para de cantar.", "En la Zona, la curiosidad mata."],
    },
    eco: {
      n: "Eco",
      role: "Cient\xEDfica superviviente",
      reg: 8,
      at: "camp",
      svc: [],
      look: { suit: 12634320, hat: "none", hair: 13684944, skin: 14203040, fem: !0 },
      greet: ["Llevo meses escondida aqu\xED. Escucho a la Mente en sue\xF1os.", "Ya casi estamos, operador."],
    },
  },
  gi = {
    m1: {
      giver: "reyes",
      main: !0,
      n: "Primer contacto",
      lvl: 1,
      xpf: 1.2,
      intro:
        "Bienvenido a Basti\xF3n, cabo. Somos la \xFAltima posici\xF3n en pie del Valle. El Enjambre cay\xF3 del cielo hace tres meses y desde entonces no hemos dejado de retroceder. Se acab\xF3. Sal ah\xED fuera y abate a 12 hostiles. Quiero ver de qu\xE9 est\xE1s hecho.",
      done: "Nada mal. Toma, esto te vendr\xE1 mejor que esa pistola.",
      obj: [{ t: "kill", any: !0, n: 12 }],
      rew: { credits: 80, items: [{ k: "weapon", base: "smg", r: 1 }], cons: { medkit: 2 } },
      next: "m2",
    },
    m2: {
      giver: "chispas",
      main: !0,
      n: "Ojos en la oscuridad",
      lvl: 2,
      xpf: 1,
      intro:
        "Hay edificios ah\xED fuera donde no entra ni un rayo de sol, y cr\xE9eme, ah\xED dentro hay cosas que adoran la oscuridad. Tr\xE1eme 4 bater\xEDas de los bichos \u2014se las comen, no preguntes\u2014 y te monto una linterna t\xE1ctica.",
      done: "Aqu\xED la tienes. Pulsa F (o LUZ, en el m\xF3vil) para encenderla o apagarla. Las zonas oscuras dejar\xE1n de ser una trampa mortal.",
      obj: [{ t: "collect", item: "Bater\xEDa", any: !0, ch: 0.3, n: 4 }],
      rew: { credits: 60, flag: "flashlight" },
      next: "m3",
    },
    m3: {
      giver: "reyes",
      main: !0,
      n: "El b\xFAnker 7",
      lvl: 3,
      xpf: 1.3,
      intro:
        "Perdimos contacto con el B\xFAnker 7, al este del valle. All\xED hab\xEDa datos de reconocimiento sobre la Reina del Enjambre. Entra, hackea su terminal principal y vuelve con esos datos. Lleva la linterna.",
      done: "Con estos datos sabemos d\xF3nde se esconde la Reina. Es hora de cortarle la cabeza a la serpiente.",
      obj: [
        { t: "reach", poi: "bunker7", n: 1 },
        { t: "hack", reg: 0, n: 1 },
      ],
      rew: { credits: 120, items: [{ k: "gear", r: 2 }] },
      next: "m4",
    },
    m4: {
      giver: "reyes",
      main: !0,
      n: "Regicidio",
      lvl: 5,
      xpf: 2,
      intro:
        "La Reina de la Plaga anida en el claro del noreste del valle. Mientras viva, el Enjambre seguir\xE1 multiplic\xE1ndose. M\xE1tala y abriremos el paso hacia la ciudad. Sube de nivel antes de ir; no es un bicho cualquiera.",
      done: "\xA1Lo has conseguido! El paso sur hacia Ciudad Ca\xEDda queda abierto. All\xED sigue habiendo supervivientes.",
      obj: [{ t: "boss", b: "reina", n: 1 }],
      rew: { credits: 300, items: [{ k: "weapon", r: 3 }] },
      next: "m5",
    },
    m5: {
      giver: "reyes",
      main: !0,
      n: "Nueva Esperanza",
      lvl: 6,
      xpf: 1,
      intro:
        "Una emisora pirata, Radio Libre, transmite desde la ciudad. Encuentra a su operadora. Ella conoce el terreno.",
      done: "",
      obj: [{ t: "talk", npc: "lucia", n: 1 }],
      rew: { credits: 100 },
      next: "m6",
    },
    m6: {
      giver: "lucia",
      main: !0,
      n: "Interferencias",
      lvl: 7,
      xpf: 1.5,
      intro:
        "\xA1Por fin alguien con un arma de verdad! Las terminales de la ciudad emiten una se\xF1al que atrae al Enjambre. Hackea 2 de ellas y podr\xE9 triangular a la bestia que lo controla todo: el Demoledor.",
      done: "Se\xF1al triangulada. El Demoledor ronda el viejo estadio, al suroeste de la ciudad.",
      obj: [{ t: "hack", reg: 1, n: 2 }],
      rew: { credits: 180, mats: { data: 2 } },
      next: "m7",
    },
    m7: {
      giver: "lucia",
      main: !0,
      n: "Derribo controlado",
      lvl: 10,
      xpf: 2,
      intro:
        "El Demoledor es un mutante del tama\xF1o de un autob\xFAs. Si cae, el camino al desierto quedar\xE1 libre. Pero ojo: all\xED el calor te cocinar\xE1 sin protecci\xF3n.",
      done: "Ha ca\xEDdo... \xA1ha ca\xEDdo de verdad! Habla con Chispas antes de cruzar al desierto.",
      obj: [{ t: "boss", b: "demoledor", n: 1 }],
      rew: { credits: 500, items: [{ k: "weapon", r: 3 }] },
      next: "m8",
    },
    m8: {
      giver: "chispas",
      main: !0,
      n: "Sangre fr\xEDa",
      lvl: 10,
      xpf: 1,
      intro:
        "El Desierto de Ceniza supera los 60 grados. Necesitas un traje refrigerado: tr\xE1eme 25 de chatarra y 10 de biomasa y te lo fabrico. Sin \xE9l, el calor te ir\xE1 quemando la vida.",
      done: "Equ\xEDpatelo antes de cruzar. Mira la resistencia al calor en tu ficha: necesitas al menos un 30%.",
      obj: [
        { t: "gather", mat: "scrap", n: 25 },
        { t: "gather", mat: "bio", n: 10 },
      ],
      rew: { credits: 100, items: [{ k: "gear", base: "s_cool", r: 2 }] },
      next: "m9",
    },
    m9: {
      giver: "reyes",
      main: !0,
      n: "Arenas de ceniza",
      lvl: 11,
      xpf: 1,
      intro: "Hay una n\xF3mada en el desierto que ha sobrevivido sola durante meses. Encu\xE9ntrala.",
      done: "",
      obj: [{ t: "talk", npc: "zahra", n: 1 }],
      rew: { credits: 150 },
      next: "m10",
    },
    m10: {
      giver: "zahra",
      main: !0,
      n: "El Rey Escorpi\xF3n",
      lvl: 15,
      xpf: 2,
      intro:
        "Kharsa. As\xED lo llamamos. Un escorpi\xF3n del tama\xF1o de una casa que se hunde en la arena y aparece bajo tus pies. M\xE1talo y te dar\xE9 algo que te har\xE1 falta en la marisma.",
      done: "Que los vientos te sean favorables. Toma este traje NBQ: en la marisma el aire te pudre los pulmones.",
      obj: [{ t: "boss", b: "kharsa", n: 1 }],
      rew: {
        credits: 800,
        items: [
          { k: "gear", base: "s_nbq", r: 2 },
          { k: "weapon", r: 3 },
        ],
      },
      next: "m11",
    },
    m11: {
      giver: "zahra",
      main: !0,
      n: "Aguas muertas",
      lvl: 15,
      xpf: 1,
      intro: "Al norte hay un ermita\xF1o loco que vive entre las esporas. Dicen que habla con ellas. B\xFAscalo.",
      done: "",
      obj: [{ t: "talk", npc: "ignacio", n: 1 }],
      rew: { credits: 200 },
      next: "m12",
    },
    m12: {
      giver: "ignacio",
      main: !0,
      n: "La Madre",
      lvl: 20,
      xpf: 2,
      intro:
        "Ella lo envenena todo. La Madre Espora late en el centro de la marisma como un coraz\xF3n podrido. Arr\xE1ncalo. Y ll\xE9vate esto para el norte: all\xED el fr\xEDo mata m\xE1s r\xE1pido que cualquier bicho.",
      done: "Las esporas callan... por primera vez en meses. El traje \xE1rtico es tuyo.",
      obj: [{ t: "boss", b: "madre", n: 1 }],
      rew: {
        credits: 1200,
        items: [
          { k: "gear", base: "s_arctic", r: 2 },
          { k: "gear", base: "b_snow", r: 2 },
        ],
      },
      next: "m13",
    },
    m13: {
      giver: "ignacio",
      main: !0,
      n: "Hielo y silencio",
      lvl: 19,
      xpf: 1,
      intro: "Una cazadora vive en la tundra. Ella conoce al Wendigo mejor que nadie.",
      done: "",
      obj: [{ t: "talk", npc: "nadia", n: 1 }],
      rew: { credits: 260 },
      next: "m14",
    },
    m14: {
      giver: "nadia",
      main: !0,
      n: "El Wendigo",
      lvl: 25,
      xpf: 2,
      intro:
        "Mat\xF3 a toda mi partida de caza. Salta como un gato y congela el aire a su alrededor. Acaba con \xE9l y el complejo Prometeo quedar\xE1 a tu alcance.",
      done: "Descansad en paz, hermanos. Gracias, operador.",
      obj: [{ t: "boss", b: "wendigo", n: 1 }],
      rew: {
        credits: 1700,
        items: [
          { k: "weapon", r: 3 },
          { k: "gear", r: 3 },
        ],
      },
      next: "m15",
    },
    m15: {
      giver: "nadia",
      main: !0,
      n: "La m\xE1quina que habla",
      lvl: 24,
      xpf: 1,
      intro:
        "En Prometeo hay una m\xE1quina que no dispara. Dice llamarse ARGOS. Quiz\xE1 sea una trampa. Quiz\xE1 no.",
      done: "",
      obj: [{ t: "talk", npc: "argos", n: 1 }],
      rew: { credits: 300 },
      next: "m16",
    },
    m16: {
      giver: "argos",
      main: !0,
      n: "Protocolo OMEGA",
      lvl: 30,
      xpf: 2.4,
      intro:
        "OPERADOR: EL PROTOTIPO OMEGA HA SIDO CORROMPIDO POR LA MENTE COLMENA. DESACTIVA 3 NODOS DE CONTROL Y DESTRUYE LA UNIDAD. TE PROPORCIONAR\xC9 PROTECCI\xD3N T\xC9RMICA PARA LA CALDERA.",
      done: "AMENAZA NEUTRALIZADA. GRATITUD: REGISTRADA. EQUIPO T\xC9RMICO ENTREGADO.",
      obj: [
        { t: "hack", reg: 5, n: 3 },
        { t: "boss", b: "omega", n: 1 },
      ],
      rew: {
        credits: 2400,
        items: [
          { k: "gear", base: "s_fire", r: 2 },
          { k: "gear", base: "h_ref", r: 2 },
        ],
      },
      next: "m17",
    },
    m17: {
      giver: "argos",
      main: !0,
      n: "Bajo el volc\xE1n",
      lvl: 29,
      xpf: 1,
      intro:
        "UN MINERO HUMANO OPERA EN LA CALDERA. SU TASA DE SUPERVIVENCIA ES ESTAD\xCDSTICAMENTE IMPOSIBLE. LOCAL\xCDZALO.",
      done: "",
      obj: [{ t: "talk", npc: "rocco", n: 1 }],
      rew: { credits: 400 },
      next: "m18",
    },
    m18: {
      giver: "rocco",
      main: !0,
      n: "El se\xF1or del fuego",
      lvl: 35,
      xpf: 2,
      intro:
        "\xA1Ifrit! As\xED lo llaman los viejos. Una monta\xF1a de magma con malas pulgas. Tr\xE1eme su cabeza y te doy el traje de plomo que guardo para el yermo.",
      done: "\xA1Ja! \xA1Ya no har\xE1 temblar mis galer\xEDas! Toma, te lo has ganado.",
      obj: [{ t: "boss", b: "ifrit", n: 1 }],
      rew: {
        credits: 3200,
        items: [
          { k: "gear", base: "s_lead", r: 2 },
          { k: "gear", base: "h_nbq", r: 2 },
        ],
      },
      next: "m19",
    },
    m19: {
      giver: "rocco",
      main: !0,
      n: "Zona de exclusi\xF3n",
      lvl: 34,
      xpf: 1,
      intro: "Un acechador llamado Viktor conoce el yermo. Te espera al este.",
      done: "",
      obj: [{ t: "talk", npc: "viktor", n: 1 }],
      rew: { credits: 500 },
      next: "m20",
    },
    m20: {
      giver: "viktor",
      main: !0,
      n: "Masa cr\xEDtica",
      lvl: 40,
      xpf: 2,
      intro:
        "El Horror Isot\xF3pico se alimenta de la radiaci\xF3n del viejo reactor. M\xE1talo y la puerta de la Colmena se abrir\xE1. Te dar\xE9 una bioarmadura que rob\xE9 a los cient\xEDficos.",
      done: "Ya est\xE1. Lo siguiente es la Colmena. Que Dios nos ayude.",
      obj: [{ t: "boss", b: "horror", n: 1 }],
      rew: { credits: 4200, items: [{ k: "gear", base: "s_bio", r: 3 }] },
      next: "m21",
    },
    m21: {
      giver: "viktor",
      main: !0,
      n: "Se\xF1ales de vida",
      lvl: 40,
      xpf: 1,
      intro: "Alguien transmite desde dentro de la Colmena. Una mujer. Encu\xE9ntrala.",
      done: "",
      obj: [{ t: "talk", npc: "eco", n: 1 }],
      rew: { credits: 600 },
      next: "m22",
    },
    m22: {
      giver: "eco",
      main: !0,
      n: "La Mente Colmena",
      lvl: 46,
      xpf: 3,
      intro:
        "La Mente est\xE1 en el centro. Todo el Enjambre, cada bicho, cada espora, responde a su voluntad. Si muere, la invasi\xF3n termina. Es nuestra \xFAnica oportunidad, operador.",
      done: "Se acab\xF3... Se ha acabado de verdad. El Enjambre se desmorona. Eres una leyenda, operador.",
      obj: [{ t: "boss", b: "mente", n: 1 }],
      rew: { credits: 9e3, items: [{ k: "weapon", r: 5 }], flag: "victory" },
    },
    s_tomas1: {
      giver: "tomas",
      n: "Plaga en los cultivos",
      lvl: 2,
      xpf: 0.8,
      intro: "Los rastreros se est\xE1n comiendo lo poco que me queda. Mata a 15 de esas alima\xF1as, por favor.",
      done: "Que Dios te lo pague. Yo solo puedo pagarte con esto.",
      obj: [{ t: "kill", e: "rastrero", n: 15 }],
      rew: { credits: 70, cons: { medkit: 2 } },
      next: "s_tomas2",
    },
    s_tomas2: {
      giver: "tomas",
      n: "Semillas perdidas",
      lvl: 3,
      xpf: 0.9,
      intro: "Los infectados se llevaron mis sacos de semillas. Algunos a\xFAn los cargan. Recupera 5.",
      done: "Con esto plantar\xE9 la cosecha de invierno. Toma, era de mi hijo.",
      obj: [{ t: "collect", item: "Saco de semillas", from: "infectado", ch: 0.35, n: 5 }],
      rew: { credits: 90, items: [{ k: "gear", r: 2 }] },
    },
    s_kai1: {
      giver: "kai",
      n: "Nidos en el valle",
      lvl: 3,
      xpf: 1,
      intro: "Los nidos de la Plaga escupen bichos sin parar. Destruye 3 y el valle respirar\xE1.",
      done: "Buen trabajo. Volver\xE1n a crecer, pero tardar\xE1n.",
      obj: [{ t: "nest", reg: 0, n: 3 }],
      rew: { credits: 110, items: [{ k: "weapon", r: 2 }] },
      next: "s_kai2",
    },
    s_kai2: {
      giver: "kai",
      n: "Registros perdidos",
      lvl: 4,
      xpf: 1,
      intro: "Las patrullas dejaron registros de datos por todo el valle antes de caer. Encuentra 3.",
      done: "Interesante... Hablan de luces en el cielo antes de la ca\xEDda.",
      obj: [{ t: "datapad", reg: 0, n: 3 }],
      rew: { credits: 140, mats: { data: 2 } },
    },
    s_lucia1: {
      giver: "lucia",
      n: "Se\xF1al de socorro",
      lvl: 8,
      xpf: 1,
      intro: "Recibo ecos de grabaciones por toda la ciudad. Encuentra 3 registros de datos.",
      done: "Gracias. Al menos sus voces no se perder\xE1n.",
      obj: [{ t: "datapad", reg: 1, n: 3 }],
      rew: { credits: 220, items: [{ k: "gear", r: 2 }] },
    },
    s_bruno1: {
      giver: "bruno",
      n: "Chatarra de calidad",
      lvl: 7,
      xpf: 0.8,
      intro: "Necesito material. 30 de chatarra y te hago precio de amigo... bueno, te pago.",
      done: "Un placer hacer negocios.",
      obj: [{ t: "gather", mat: "scrap", n: 30 }],
      rew: { credits: 300, items: [{ k: "weapon", r: 2 }] },
      next: "s_bruno2",
    },
    s_bruno2: {
      giver: "bruno",
      n: "Caza mayor",
      lvl: 9,
      xpf: 1.2,
      intro: "Un cliente paga bien por trofeos de \xE9lite. Mata a 5 enemigos de \xE9lite.",
      done: "\xA1Mi cliente estar\xE1 encantado!",
      obj: [{ t: "kill", any: !0, elite: !0, n: 5 }],
      rew: { credits: 450, items: [{ k: "weapon", r: 3 }] },
    },
    s_zahra1: {
      giver: "zahra",
      n: "Agua bajo la arena",
      lvl: 12,
      xpf: 1,
      intro: "Los gusanos de arena almacenan agua en gl\xE1ndulas. Tr\xE1eme 6, mi gente tiene sed.",
      done: "Hoy beberemos gracias a ti.",
      obj: [{ t: "collect", item: "Gl\xE1ndula de agua", from: "gusano", ch: 0.4, n: 6 }],
      rew: { credits: 400, items: [{ k: "gear", base: "h_ref", r: 2 }] },
    },
    s_zahra2: {
      giver: "zahra",
      n: "Tormenta de aguijones",
      lvl: 13,
      xpf: 1,
      intro: "Los escorpiones rodean el oasis. Mata a 20.",
      done: "El oasis vuelve a ser seguro.",
      obj: [{ t: "kill", e: "escorpion", n: 20 }],
      rew: { credits: 450, items: [{ k: "weapon", r: 2 }] },
    },
    s_ign1: {
      giver: "ignacio",
      n: "Muestras de esporas",
      lvl: 16,
      xpf: 1,
      intro: "Los hongos caminantes llevan esporas madre. Tr\xE1eme 8. Las necesito para... cosas.",
      done: "S\xED, s\xED... Perfectas. Toma esto, me sobra.",
      obj: [{ t: "collect", item: "Espora madre", from: "hongo", ch: 0.45, n: 8 }],
      rew: { credits: 600, items: [{ k: "gear", base: "i_detox", r: 2 }] },
    },
    s_ign2: {
      giver: "ignacio",
      n: "Sangr\xEDa",
      lvl: 17,
      xpf: 1,
      intro: "Las sanguijuelas se reproducen como la peste. Elimina 25.",
      done: "El agua est\xE1 algo menos roja. Algo.",
      obj: [{ t: "kill", e: "sanguijuela", n: 25 }],
      rew: { credits: 650, mats: { bio: 15 } },
    },
    s_nadia1: {
      giver: "nadia",
      n: "La manada blanca",
      lvl: 20,
      xpf: 1.1,
      intro: "Los yetis mutantes cazan en manada. Abate a 6.",
      done: "Buenas pieles. Bueno, mutantes. Pero buenas.",
      obj: [{ t: "kill", e: "yeti", n: 6 }],
      rew: { credits: 800, items: [{ k: "gear", base: "h_therm", r: 3 }] },
    },
    s_nadia2: {
      giver: "nadia",
      n: "Corazones de hielo",
      lvl: 21,
      xpf: 1,
      intro: "Los elementales llevan n\xFAcleos helados. Valen oro. Tr\xE1eme 6.",
      done: "Esto mantendr\xE1 el campamento caliente... ir\xF3nicamente.",
      obj: [{ t: "collect", item: "N\xFAcleo helado", from: "elhielo", ch: 0.4, n: 6 }],
      rew: { credits: 900, mats: { crystal: 6 } },
    },
    s_argos1: {
      giver: "argos",
      n: "Purga de sistemas",
      lvl: 25,
      xpf: 1,
      intro: "UNIDADES MEC\xC1NICAS CORROMPIDAS DETECTADAS: 1.204. SOLICITO LA ELIMINACI\xD3N DE 30.",
      done: "EFICIENCIA: ACEPTABLE.",
      obj: [{ t: "kill", fam: "mech", n: 30 }],
      rew: { credits: 1100, mats: { core: 4 } },
    },
    s_rocco1: {
      giver: "rocco",
      n: "Fiebre del cristal",
      lvl: 30,
      xpf: 1,
      intro: "Tr\xE1eme 10 cristales xeno. Pago bien. Muy bien.",
      done: "\xA1Preciosos! \xA1Preciosos!",
      obj: [{ t: "gather", mat: "crystal", n: 10 }],
      rew: { credits: 2200, items: [{ k: "weapon", r: 3 }] },
    },
    s_viktor1: {
      giver: "viktor",
      n: "Artefactos de la Zona",
      lvl: 35,
      xpf: 1,
      intro: "Los registros de los cient\xEDficos est\xE1n dispersos por el yermo. Encuentra 3.",
      done: "Esto... explica muchas cosas. Toma.",
      obj: [{ t: "datapad", reg: 7, n: 3 }],
      rew: { credits: 2600, items: [{ k: "gear", r: 3 }] },
    },
    s_eco1: {
      giver: "eco",
      n: "Guardianes",
      lvl: 41,
      xpf: 1.2,
      intro: "Los guardianes de la colmena protegen los accesos. Abate a 6.",
      done: "El camino est\xE1 m\xE1s despejado.",
      obj: [{ t: "kill", e: "guardian", n: 6 }],
      rew: { credits: 4e3, items: [{ k: "weapon", r: 4 }] },
    },
    s_lin1: {
      giver: "lin",
      n: "Muestras xeno",
      lvl: 3,
      xpf: 0.8,
      intro:
        "Necesito 12 muestras de biomasa para empezar a investigar al Enjambre. A cambio podr\xE9 mejorar tus capacidades de forma permanente.",
      done: "\xA1Excelente! El laboratorio ya est\xE1 operativo. Vuelve con materiales para investigar mejoras.",
      obj: [{ t: "gather", mat: "bio", n: 12 }],
      rew: { credits: 100, flag: "research" },
      next: "s_lin2",
    },
    s_lin2: {
      giver: "lin",
      n: "Anatom\xEDa de \xE9lite",
      lvl: 8,
      xpf: 1,
      intro: "Los espec\xEDmenes de \xE9lite tienen tejidos \xFAnicos. Tr\xE1eme 4 muestras de tejido de \xE9lite.",
      done: "Esto es... asombroso. Toma, he sintetizado algo para ti.",
      obj: [{ t: "collect", item: "Tejido de \xE9lite", any: !0, elite: !0, ch: 0.7, n: 4 }],
      rew: { credits: 300, items: [{ k: "gear", base: "m_xeno", r: 3 }] },
    },
    s_vega1: {
      giver: "vega",
      n: "Prueba de tiro",
      lvl: 2,
      xpf: 1,
      intro: "\xBFQuieres descuento? Demu\xE9strame que sabes usar lo que vendo. 40 bajas.",
      done: "Vale, vale. Te has ganado mi respeto. Y un regalito.",
      obj: [{ t: "kill", any: !0, n: 40 }],
      rew: { credits: 150, items: [{ k: "weapon", r: 2 }] },
    },
    s_nav1: {
      giver: "navarro",
      n: "Bautismo de fuego",
      lvl: 4,
      xpf: 1.3,
      intro:
        "Completa tu primera operaci\xF3n especial. Usa mi terminal de despliegue o cualquier brecha que encuentres en el mundo.",
      done: "Has vuelto entero. Eso ya es mucho.",
      obj: [{ t: "op", n: 1 }],
      rew: { credits: 250, items: [{ k: "gear", r: 3 }] },
    },
  },
  gx = [
    "Placa de identificaci\xF3n",
    "Muestra de tejido",
    "Componente electr\xF3nico",
    "Diario personal",
    "C\xE1psula de datos",
    "Fragmento de caparaz\xF3n",
  ],
  xx = [
    { t: "kill_e", w: 10, n: [14, 30], title: (n) => `Control de plagas: ${n}` },
    { t: "kill_fam", w: 6, n: [25, 45], title: (n) => `Ofensiva contra ${n}` },
    { t: "elite", w: 4, n: [3, 6], title: () => "Caza de \xE9lites" },
    { t: "nest", w: 3, n: [2, 4], title: () => "Esterilizaci\xF3n" },
    { t: "gather", w: 4, title: (n) => `Suministros: ${n}` },
    { t: "collect", w: 5, n: [4, 8], title: (n) => `Recuperar ${n.toLowerCase()}` },
    { t: "op", w: 3, n: [1, 1], title: () => "Operaci\xF3n encubierta" },
    { t: "event", w: 3, n: [1, 2], title: () => "Respuesta r\xE1pida" },
    { t: "hack", w: 2, n: [1, 2], title: () => "Guerra electr\xF3nica" },
  ];

